[tools]
python = "3.13"
node = "latest"
"npm:ansible-language-server" = "latest"

[env]
ANSIBLE_FORCE_COLOR = "True"
_.python.venv = {path = ".venv", create = true }

[tasks.init]
run = """
pip install --upgrade pip
pip install -r requirements.txt
ansible-galaxy install -r requirements.yml --force
"""

[tasks.playbook]
run = ['./run.sh ansible-playbook -K ']


