- name: Check if repo directory exists
  stat:
    path: "{{ project_dir }}"
  register: repo_directory

- name: Clone git repo
  git:
    repo: "{{ git_repo }}"
    dest: "{{ project_dir }}"
    update: yes
  when: not repo_directory.stat.exists
  become: yes
  notify: Restart the DNS

- name: Check if podman container exists
  command: podman image exists {{ image_name }}
  register: result
  failed_when: result.rc == 125
  changed_when: false
  become: yes

- name: Build the podman container
  command: make build
  args:
    chdir: "{{ project_dir }}"
  when: result.rc == 1
  become: yes
  notify: Restart the DNS



