- name: Check if podman container is running
  shell: podman ps -qa --filter "name={{ image_name }}"
  register: container_status
  ignore_errors: true
  changed_when: false
  become: yes

- name: Stop the running DNS image
  command: make stop
  args:
    chdir: "{{ project_dir }}"
  when: container_status.stdout != ''
  become: yes

- name: Make sure the podman container is running
  include_tasks: ./start-dns.yml
