- name: Stop systemd-resolve if running
  systemd:
    name: systemd-resolved
    state: stopped
  become: yes

- name: Disable systemd-resolve
  systemd:
    name: systemd-resolved
    enabled: no
  become: yes

- name: Check if podman container is running
  shell: podman ps -qa --filter "name={{ image_name }}"
  register: container_status
  ignore_errors: true
  changed_when: false
  become: yes

- name: Run the DNS image
  command: make start
  args:
    chdir: "{{ project_dir }}"
  become: yes
  when: container_status.stdout == ''
