all:
  hosts:
    wolfden:
    wolfpaw:
    bite:
    wolftrack:
    carnivore:

down:
  hosts:

purposes:
  children:
    servers:
      hosts:
        wolfpaw:
        bite:
        wolftrack:
      vars:
        headless: true

    desktop:
      hosts:
        wolfden:

    laptops:
      hosts:
        carnivore:

    dns_servers:
      hosts:
        bite:

    podman_hosts:
      hosts:
        bite:
        wolfpaw:
        carnivore:

platforms:
  children:
    arch:
      hosts:
        wolfden:
        wolfpaw:
        bite:

    endeavour:
      hosts:
        carnivore:

    synology:
      hosts:
        wolftrack:

groups:
  children:
    linux:
      children:
        arch:
        endeavour:
        synology:

    arch_based:
      children:
        arch:
        endeavour:
