---

- name: Update arch packages
  include_tasks: update.yml
  tags:
    - setup
    - update

- name: Install necessary arch packages
  include_tasks: packages.yml
  tags:
    - setup

# - name: Install software from installers list
#   include_tasks: ../../shared/tasks/check_and_install.yml
#   loop: "{{ installers }}"
#   tags:
#     - setup

- name: Install user configurations
  include_tasks: ../../shared/tasks/git-sparse-checkout.yml
  vars:
    repo_url: "{{ config_repo_url }}"
    branch: "{{ config_branch }}"
    base_dir: "{{ lookup('env', 'HOME') }}/.config"
    config_files: "{{ configs }}"
  tags:
    - setup
    - update

- name: Ensure services are running
  include_tasks: services.yml
  tags:
    - setup
    - update

- name: Harden the configurations
  include_tasks: harden.yml
  tags:
    - hardening
