---

- name: Update arch packages
  include_tasks: update.yml
  tags:
    - setup
    - update

- name: Install necessary arch packages
  include_tasks: packages.yml
  tags:
    - setup

- name: Harden the configurations
  include_tasks: harden.yml
  tags:
    - hardening
