---

- name: Install headless packages
  pacman:
    name: "{{ packages.headless }}"
    state: present
  ignore_errors: true
  become: true

- name: Install graphical packages
  pacman:
    name: "{{ packages.graphical }}"
    state: present
  when: headless is not defined or not headless
  ignore_errors: true
  become: true

- name: Install software from installers list
  include_tasks: ../../shared/tasks/check_and_install.yml
  loop: "{{ installers }}"
  tags:
    - setup

