---

- hosts: localhost
  connection: local
  tasks:
    
    - name: dependencies | Install dependency packages
      ansible.builtin.dnf:
        name: 
          - gcc-c++
        state: present
      become: true

