# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Load all the modular configuration files
for file in ~/.bashrc.d/*; do
  if [[ -r "${file}" ]]; then
    source "${file}"
  else
    print_error "Unable to read ${file}. Skipping."
  fi
done

