---
packages:
  headless:
    #development
    - gcc
    - make
    - cmake
    - python
    #cli tools
    - vim
    - exa
    - bat
    - helix
    - git
    - fd
    - ripgrep
    #system
    - htop
    - bash-completion
    - keychain
    - procs
    - pueue
    #network
    - networkmanager
    - networkmanager-openvpn
    - networkmanager-openconnect
    - nfs-utils
    - curl
    - openssh
    - rsync
    - nmap
    #security
    - firewalld
    #ldap
    - sssd
    - nss-pam-ldapd
    # shell customization
    - vivid
    - thefuck
    - starship
    - ttf-firacode-nerd

  graphical:
    # productivity
    - firefox
    # misc
    - flameshot
    - gammastep
    # misc
    - alacritty

enabled_services:
  - sshd
  - firewalld
  - NetworkManager

# Disable unused services
unused_services:
  - avahi-daemon
  - cups
  - ufw

config_repo_url: https://github.com/MightBeAWolf/dot-config.git
config_branch: main
configs:
  - helix
  - thefuck
  - starship.toml
  
