# tasks/main.yml
---
- name: Copy .bashrc if needed
  copy:
    src: bashrc
    dest: "~/.bashrc"
    mode: '0750'

- name: Copy .bashrc.d/ directory if needed
  copy:
    src: bashrc.d/
    dest: "~/.bashrc.d"
    mode: '0750'
