# tasks/main.yml
---
- name: Ensure Git is installed
  package:
    name: git
    state: present

- name: Clone bashrc repository
  git:
    repo: 'https://github.com/MightBeAWolf/bashrc.git'
    dest: ~/.bashrc.d

- name: Create soft link for bashrc
  file:
    src: ~/.bashrc.d/bashrc
    dest: ~/.bashrc
    state: link
    force: yes

