# tasks/main.yml
---
- name: Install software from installers list
  include_tasks: check_and_install.yml
  loop: "{{ installers }}"

- name: Ensure Git is installed
  package:
    name: git
    state: present

- name: Clone bashrc repository
  git:
    repo: '{{ bashrc_repo_url }}'
    dest: ~/.bashrc.d

- name: Create soft link for bashrc
  file:
    src: ~/.bashrc.d/bashrc
    dest: ~/.bashrc
    state: link
    force: yes

