---

- hosts: arch_based
  roles:
    - role: arch-based
    - role: bash-env
    - role: podman

- hosts: linux
  roles:
    - role: bash-env

# Not synology linux machines
- hosts: linux:!synology:!down
  roles:
    # - role: dns-client

###################################
####### Host Specific Roles #######
###################################
- hosts: carnivore
  roles:
    - role: sway

- hosts: wolfden
  roles:
    - role: hyperland

- hosts: bite
  roles:
    - role: dns-server
