---

- hosts: arch_based
  roles:
    - role: arch-based
    - role: bash-env
    - role: podman
    - role: home-env

- hosts: linux
  roles:
    - role: bash-env

# Not synology linux machines
- hosts: linux:!synology:!down
  roles:
    # - role: dns-client

###################################
####### Host Specific Roles #######
###################################
- hosts: carnivore
  roles:
    - role: sway

- hosts: bite
  roles:
    - role: dns-server
