---
- hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.setup:

- ansible.builtin.import_playbook: "dependencies/main.yml"

- hosts: localhost
  connection: local
  roles:
    - role: bash-env
    - role: package-1password
    - role: ldap_client
    - role: harden
      tags: ['harden', 'security']

- ansible.builtin.import_playbook: "distro/main.yml"


