---
- hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.setup:

- ansible.builtin.import_playbook: "dependencies/main.yml"

- hosts: localhost
  connection: local
  roles:
    - role: bash-env

- ansible.builtin.import_playbook: "distro/main.yml"


