---
packages:
  # Greeter
  - greetd
  - greetd-tuigreet

  # Main Window Manager Components
  - sway # Window Manager
  - swaybg
  - swayidle
  - swaylock
  - waybar # Status Bar
  - mako # Notification System
  - polkit
  - polkit-gnome

  # Audio
  - pipewire #Low-latency audio/video router and processor
  - pipewire-alsa #Low-latency audio/video router and processor - ALSA configuration
  - pipewire-audio #Low-latency audio/video router and processor - Audio support
  - pipewire-pulse #Low-latency audio/video router and processor - PulseAudio replacement
  - wireplumber #Session / policy manager implementation for PipeWire
  - gst-plugin-pipewire #Multimedia graph framework - pipewire plugin
  - libpipewire #Low-latency audio/video router and processor - client library
  - libwireplumber #Session / policy manager implementation for PipeWire - client library

  # Additional Packages
  - copyq
  - gammastep

installers:
  - name: "Rust"
    check: "test -e ${HOME}/.cargo/bin/cargo"
    file: "00-rust.sh"

config_repo_url: https://github.com/MightBeAWolf/dot-config.git
config_branch: main
configs:
  - sway
  - swaylock
  - waybar
  - copyq
  - alacritty
  - gammastep
  - background.jpg

